"""add soft-delete (deleted_at) for applications and candidates

Revision ID: a4e999b17d1c
Revises: a2b3c4d5e6f7
Create Date: 2026-09-10 03:43:44.246297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e999b17d1c'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_applications_deleted_at'), 'applications', ['deleted_at'], unique=False)
    op.add_column('candidates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_candidates_deleted_at'), 'candidates', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_deleted_at'), table_name='candidates')
    op.drop_column('candidates', 'deleted_at')
    op.drop_index(op.f('ix_applications_deleted_at'), table_name='applications')
    op.drop_column('applications', 'deleted_at')
    # ### end Alembic commands ###
